# dev env for Jekyll or theme upgrade
services:
  jekyll:
    image: ruby:3.3
    container_name: optimus-blog-dev
    volumes:
      - ./:/home/Optimus-Xs.github.io/
    ports:
      - "4000:4000"
      - "35729:35729"
    entrypoint: [ "/bin/bash" ]
    stdin_open: true
    tty: true